### ISSUE TITLE
Не могу добавить ветку в pull requests, для решения задачи

### ISSUE THREAD

**Issue by Sasha1239** [pen-dev/weather-cli#11]
При нажатии на **new pull requests** у меня выбирается другой проект (откуда ты форкнул) [см. вложение](https://user-images.githubusercontent.com/68199637/100516366-72731e80-3194-11eb-9310-0144d0b03d46.png), а после того, как выбираю твой проект, то не могу добавить ветку [см. скрин](https://user-images.githubusercontent.com/68199637/100516404-af3f1580-3194-11eb-97e2-1ea8f0b49c6e.png)
Доп. вопрос: нужно ли устанавливать git flow? Я думаю, что нет необходимости, т.к. по идее можно закрыть потребности существующим функционалом.

**Comment by pen-dev** [comment]
@Sasha1239 

> нужно ли устанавливать git flow?

А что ты имеешь ввиду? (лучше ссылку на то что думал установить)

>При нажатии на new pull requests у меня выбирается другой проект (откуда ты форкнул) см. вложение, а после того, как выбираю твой проект, то не могу добавить ветку см. скрин

А новая ветка в твоем форке есть ? Лучше пока работать в моей [ветке](https://github.com/pen-dev/weather-cli/pull/10)(я ее специально сделал для тебя), чтобы не вникать в настроки окружения и пр, а сразу перейти в работу с кодом.

**Comment by pen-dev** [comment]
![image](https://user-images.githubusercontent.com/36673959/100538131-cd615000-323e-11eb-8e7d-8be131c2695b.png)


а просто вставить картинку не получается?

**Comment by Sasha1239** [comment]
Вставить можно, думал,что так удобнее будет. Просто я хотел к каждому заданию сделать ветку и чтобы в ней решал задачу.

**Comment by pen-dev** [comment]
> Просто я хотел к каждому заданию сделать ветку и чтобы в ней решал задачу.

Идея правильная, но пока лучше ее отложить и сосредоточиться на задаче. А к этому потом вернемся, пока что ветка есть - используй ее как использовал бы свою

**Comment by Sasha1239** [comment]
Окей, понял
