### ISSUE TITLE
Внезапно появилась загрузка и иконка текущей ветки и репозитория

### ISSUE THREAD

**Issue by Sasha1239** [pen-dev/weather-cli#12]
Не понимаю, откуда мог взяться репозиторий a.sherbakov, когда работал только в Autotest_cypress. С чем это может быть связано?
![image](https://user-images.githubusercontent.com/68199637/107779084-f1b8cd00-6d55-11eb-829d-6c19b1b0d22b.png)
![image](https://user-images.githubusercontent.com/68199637/107779262-2a58a680-6d56-11eb-972e-1c0c0fa8694c.png)

**Comment by pen-dev** [comment]
А можешь прислать вывод в терминал(тот что на скрине) текстом?@Sasha1239

**Comment by Sasha1239** [comment]
Я кажется разобрался, уже в тот день,когда создал, у меня проект назывался в cypress a.sherbakov,а репозиторий по-другому, когда пушил скорее всего и создался репозиторий,потом удалил a.sherbskov, переименовал в cypress проект, используя название репозитория, и больше такого не было
